ledger:
  networks: "mainnet=grpc.seed1.ap.cheqd.net:9090;testnet=159.89.208.88:443"
  timeout: "5s"

resolver:
  method: "cheqd"

api:
  listener: "0.0.0.0:1313"
  resolverPath: "/1.0/identifiers/:did"

logLevel: "warn"
