resolver:
  method: "cheqd"
  networks: "mainnet=rpc.cheqd.net:443;testnet=159.89.208.88:443"
  ledgerTimeout: "5s"

api:
  listener: "0.0.0.0:1313"
  resolverPath: "/1.0/identifiers/:did"

logLevel: "debug"
