version: '3.7'


services:
  did_resolver:
    build:
      dockerfile: Dockerfile
    user: root
    configs:
      - source: config
        target: /root/config.yml
    expose:
      - ${RESOLVER_PORT:-1313}
      - 9090
    ports:
      - "${RESOLVER_PORT:-1313}:${RESOLVER_PORT:-1313}"
    profiles:
      - resolver

  redirect:
    image: morbz/docker-web-redirect
    restart: always
    ports:
      - "${REDIRECTED_PORT:-80}:${REDIRECTED_PORT:-80}"
    environment:
      - VIRTUAL_HOST=localhost:80
      - REDIRECT_TARGET=${CHEQD_RESOLVER_PATH:-http://localhost:1313}
    profiles:
      - driver

configs:
  config:
    file: config.yml