name: "Build"
on:
  workflow_call:

jobs:

  check-building:
    name: "Check binary build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Run Golang build
        run: go build main.go

  try-docker-build:
    name: "Check docker build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check docker building
        working-directory: .
        run: docker build -f docker/Dockerfile -t cheqd-did-resolver .

      - name: Save cheqd-did-resolver Docker image
        run: docker save -o cheqd-did-resolver.tar cheqd-did-resolver

      - name: Store cheqd-did-resolver artifact
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-did-resolver.tar
          path: cheqd-did-resolver.tar
