name: "Build"
on:
  workflow_call:

jobs:

  check-building:
    name: "Check binary building"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Run Golang build
        run: go build main.go

  try-docker-build:
    name: "Check docker building"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check docker building
        working-directory: .
        run: docker build -f docker/Dockerfile .